# Generated by Django 4.2.4 on 2023-12-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('en_no', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
                ('img', models.ImageField(upload_to='./img')),
            ],
        ),
    ]
