# Generated by Django 4.2.4 on 2023-12-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='img',
            field=models.ImageField(upload_to='./img/'),
        ),
    ]
