# Generated by Django 4.2.4 on 2023-12-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0002_alter_register_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
