# Generated by Django 4.2.7 on 2023-12-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0003_alter_register_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
