# Generated by Django 4.2.4 on 2024-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0004_register_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cap_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
