# Generated by Django 4.2.4 on 2024-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0006_alter_register_cap_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='cap_img',
            field=models.ImageField(upload_to='cap_images/'),
        ),
    ]
