# Generated by Django 5.0 on 2023-12-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attending_class',
            fields=[
                ('en_no', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('attended', models.BooleanField()),
            ],
        ),
    ]
